---
title: "Investigaciones de acceso abierto"
---

Este es un sitio web que alberga un proyecto de investigación realizado para la cátedra Estadística multivariada. Pero que fue adaptado para su accesibilidad y reproducibilidad para el elecitvo de profundización metodológica: Ciencia Social Abierta, herramientas para la Reproducibilidad, Colaboración y Comunicación de la Investigación Social

Por ello este proyecto posee dos autores distintos:

la y los creadores del trabajo (Cátedra estadística): 

- Mayron Vasquez, 
- Ignacio Núñez, 
- Nicolás Tobar, 
- Alexis Ibáñez y 
- Dafne Jaime Vargas. 

Grupo 1 Legitimidad política y posición social

las y los reproductores del trabajo (para el electivo): 

- Mayron Vasquez, 
- Danae Pedraza, 
- Alvaro Serrano y 
- Dafne Jaime Vargas. 

Grupo 9

Para este proceso se contó con la autorización de TODOS los creadores del contenido.

Esta entrega posee un formato reproducible [IPO](https://juancarloscastillo.github.io/ipo/)

Esta entrega se basa en la encuesta [CEP N°83 de Mayo del 2019.](https://www.cepchile.cl/cep/encuestas-cep/encuestas-2009-2018/estudio-nacional-de-opinion-publica-mayo-2019)

Tambien puede encontar el proyecto de investigación [aquí](https://osf.io/796bf/) (OSF).
